name: flutter_demo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_secure_storage: ^4.1.0

  get: ^4.1.4

  hive: ^2.0.4

  internet_connection_checker: ^0.0.1

  intl: ^0.17.0

  logger: ^1.0.0

  pedantic: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
